param(
    [ValidateSet('start-db','db-ready','alembic-current','alembic-upgrade','alembic-revision','all')]
    [string]$Task = 'all',
    [string]$Message = 'auto'
)

function Start-Db {
    Write-Host 'Starting postgres container...' -ForegroundColor Cyan
    docker compose up -d db | Out-Host
}

function Db-Ready {
    Write-Host 'Checking postgres readiness...' -ForegroundColor Cyan
    docker compose exec db pg_isready -U postgres | Out-Host
}

function Show-DatabaseUrl {
    Write-Host 'DATABASE_URL from .env:' -ForegroundColor DarkCyan
    & venv\Scripts\python -c "from dotenv import load_dotenv; load_dotenv(); import os; print(os.getenv(''DATABASE_URL''))" | Out-Host
}

function Alembic-Current {
    Write-Host 'Alembic current:' -ForegroundColor Cyan
    alembic current | Out-Host
}

function Alembic-Upgrade {
    Write-Host 'Alembic upgrade head...' -ForegroundColor Cyan
    alembic upgrade head | Out-Host
}

function Alembic-Revision {
    param([string]$Msg)
    if (-not $Msg -or $Msg -eq 'auto') { $Msg = 'autogenerated' }
    Write-Host "Alembic revision --autogenerate -m '$Msg'" -ForegroundColor Cyan
    alembic revision --autogenerate -m "$Msg" | Out-Host
}

switch ($Task) {
    'start-db'         { Start-Db }
    'db-ready'         { Db-Ready }
    'alembic-current'  { Alembic-Current }
    'alembic-upgrade'  { Alembic-Upgrade }
    'alembic-revision' { Alembic-Revision -Msg $Message }
    'all'              {
        Start-Db
        Db-Ready
        Show-DatabaseUrl
        Alembic-Upgrade
        Alembic-Current
    }
}
