"""create users,vocab,user_progress

Revision ID: 96ff5ab5206d
Revises: a98dfebc8646
Create Date: 2025-09-10 09:15:51.816645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ff5ab5206d'
down_revision: Union[str, Sequence[str], None] = 'a98dfebc8646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
